### ISSUE TITLE
Não consigo instalar

### ISSUE THREAD

**Issue by callmesideshow** [KitsuneSemCalda/Animatic-v2#12]
![image](https://github.com/user-attachments/assets/3b594507-9543-4e87-bc50-b46b819e377d)
Não sei porque ocorre :(

**Comment by KitsuneSemCalda** [comment]
você está rodando o script como root.

Normalmente, ele pediria a senha de sudo (no usuário default) quando roda 

```bash
bash ./install.sh
```

e usaria as informações das variáveis de ambiente para montar o path. 

Exemplo: /home/kitsunesemcalda/.local/bin para instalar o projeto, já que ele configuraria o $PATH. 

Outro problema que ocorre é que ele não encontrou a versão 1.21.5 do Go somente a versão 1.22.5
